# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ec38fdf9055c635b1512795c337e365eb14fe639b80d9e4078a91bb65d5b121e6787716321e59f38bb182afa52b4a0f6424239bc44049ec4455ffce6706e859

test:
  secret_key_base: 964acef07be15490d1bd6abc2acc2bc90a26ce93cce9d67682da62a9c0def1665f93fd6504a52997b4cedd2cf103d6562e85cf2a938d52cce08f7361297ea993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
